batch_size: 32
height: 96
learning_rate: 0.0005
max_text_length: 93
model_path: Model/202404021423
train_epochs: 26
train_workers: 25
vocab: gk?OBeRz73lFrKbYQWtNmZ9+uwfd"GSJ&:6VpTA!;EU4'o/C,*H jX)Iyxih-P0as8(.c25#nMLvq1D
width: 1408
